title: Symprix
description: Strategic advisory in rail economics and infrastructure investment.
url: "https://www.symprix.com"
baseurl: "" # leave this as-is for root domain
author: Sidi Sun
email: sidi.sun@symprix.com
