# Site settings
title: Symprix
email: info@symprix.com
description: > 
Symprix is a strategic advisory practice helping transport, infrastructure, and innovation leaders move from complexity to clarity.
baseurl: "" 
url: "https://www.symprix.com"

twitter_username:
github_username: CD-Symprix

# Build settings
markdown: kramdown
